### PR TITLE
Benchmark

### PR DESCRIPTION
**Pull request by AndreasMadsen**
@MarcoDalFarra I made a pull request for you. So you can get some feedback.

### CODE REVIEW

**Comment by AndreasMadsen** [comment]
- You should consider adding:

```
{
  "ensure_newline_at_eof_on_save": true,
  "trim_trailing_white_space_on_save": true,
  "translate_tabs_to_spaces": true,
  "tab_size": 4,
  "rulers": [80]
}
```

to your sublime text settings, to prevent many of the `pep8` issues.

---

I don't know if this is ready, but:
- Remember to update the `build.mk` files such that `make clean all` passes without errors.
- Update the `python_reference` `SparsemaxRegression` class such the API is the same, for the other `SparsemaxRegression` classes you created.
- Setup cross validation, similar to what I did in [python-reference/test/test_sparsemax_regression.py#ModelTest](https://github.com/AndreasMadsen/course-02456-sparsemax/blob/master/python-reference/test/test_sparsemax_regression.py) in the benchmark script.

**Comment by copaah** [comment]
@AndreasMadsen Thanks! I'm planning to look further into it today and tomorrow :)

**Comment by copaah** [comment]
Fixed paths and errors in build and make files. Added cross validation. I'm still having some troubles in designing the interfaces for the three SparsemaxRegression classes - suggestions are welcom! It's not clear to me how to pass the tensorflow graph between methods inside the class. The numpy implementation is currently not working either. I will probably look at it again sunday and/or monday morning.

**Comment by AndreasMadsen** [comment]
> Fixed paths and errors in build and make files. Added cross validation. I'm still having some troubles in designing the interfaces for the three SparsemaxRegression classes - suggestions are welcom! It's not clear to me how to pass the tensorflow graph between methods inside the class. The numpy implementation is currently not working either. I will probably look at it again sunday and/or monday morning.

You need to create a session that shared for the entire model. I suggest you use the `__enter__` and `__exit__` magic methods. I have uploaded an example here: https://github.com/AndreasMadsen/course-02456-sparsemax/commit/601f018144198f652c288c26ea6594771e0c86cb

The example I have uploaded uses almost (changed random_state propagation) the same API as the original numpy regression model, so it should be _fairly easy_ to make it work.

**Pull request merged**
